# Dockerfile.jinja2 for multi-stage build
FROM python:3.12-slim AS build_{{cookiecutter.project_build_id}}
WORKDIR /env
COPY  app /env/app/
COPY pyproject.toml /env/pyproject.toml

RUN python -m venv .venv
#Install uv using custom index from secret
RUN --mount=type=secret,id=pip_index_url \
    .venv/bin/pip install uv -i "$(cat /run/secrets/pip_index_url)"


# Install agent requirements using custom index from secret
RUN --mount=type=secret,id=pip_index_url \
    .venv/bin/uv sync --all-groups  --index-url "$(cat /run/secrets/pip_index_url)" 


RUN --mount=type=secret,id=pip_index_url \
    .venv/bin/uv lock --index-url "$(cat /run/secrets/pip_index_url)"