[dependency-groups]
servicelayer = [
    "pydantic>=2.0",
    "cryptography>=45.0.6",
    "fastapi>=0.116.1",
    "httpx>=0.28.1",
    "pyjwt>=2.10.1",
    "requests>=2.32.5",
    "uvicorn>=0.35.0",
    "pydantic-settings>=2.10.1",
    "colorlog"
]




